CREATE TABLE users ( user_id varchar(36), user_name varchar(512), CONSTRAINT user_id PRIMARY KEY (user_id));

CREATE TABLE records (record_id varchar(36), author_id varchar(36), title varchar(512), text varchar(2048), CONSTRAINT record PRIMARY KEY (record_id));

CREATE TABLE tags (tag_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL, tag_name varchar, CONSTRAINT tag_id PRIMARY KEY (tag_id));

CREATE TABLE tags_records (tag_id int, record_id varchar(36));

ALTER TABLE records ADD FOREIGN KEY (author_id) REFERENCES users (user_id);

ALTER TABLE tags_records ADD FOREIGN KEY (tag_id) REFERENCES tags (tag_id) ON DELETE CASCADE;

ALTER TABLE tags_records ADD FOREIGN KEY (record_id) REFERENCES records (record_id) ON DELETE CASCADE;